using
    SparseArrays,
    MetaGraphsNext,
    Graphs,
    DataStructures,
    Distances,
    JuMP,
    HiGHS,
    LinearAlgebra,
    Printf,
    ProgressMeter

export
    TwwlPrim,
    treeMetricLP

"""
    Node struct

    This struct represents a node in a label tree.

    - hash::UInt
        label generated by WL algorithm
    - depth::Int
        the depth of this node in a label tree
    - Γ::AbstractVector
        Γ[i] is the same value described in our paper
    - children::Vector{Tuple{Float64,Node}}
        A collection of this node’s children.
        Each element is a `(weight, child_node)` tuple, where the first element (`Float64`) represents the edge weight to the child, and the second element is the child `Node` itself.
"""
struct Node
    hash::UInt
    depth::Int
    Γ::AbstractVector
    children::Vector{Tuple{Float64,Node}}
end
function Base.show(io::IO, node::Node)
    text = @sprintf("""
        ----------[Node struct]----------
        hash: %d
        depth: %d
        isleaf: %s
        ---------------------------------""",
        node.hash, node.depth, length(node.children) == 0
    )

    print(io, text)
end

"""
    TwwlPrim(H::Int)

    This returns a TwwlPrim struct with the given maximum depth `H`.
    This data structure exactly matches the one described in our paper,
    and has not been optimized in order to readability.

    - root::Node
        The root node of the label tree.
"""
mutable struct TwwlPrim
    H::Int
    N::Union{Nothing,Int}
    labelSymb::Symbol
    measureSymb::Symbol
    root::Union{Nothing,Node}
    labelSeq::Union{Nothing,Vector{AbstractMatrix}}
    measures::Union{Nothing,Vector{AbstractVector}}
end
function TwwlPrim(H::Int; labelSymb::Symbol=:label, measureSymb::Symbol=:measure)
    _checkH(H)
    return TwwlPrim(H, nothing, labelSymb, measureSymb, nothing, nothing, nothing)
end
function Base.show(io::IO, kernel::TwwlPrim)
    text = @sprintf("""
        ----------[Primitive Twwl struct]----------
        H: %d
        labelSymb: :%s
        measureSymb: :%s
        Is fitted: %s
        ---------------------------------""",
        kernel.H,
        String(kernel.labelSymb),
        String(kernel.measureSymb),
        isnothing(kernel.root) && isnothing(kernel.labelSeq) && isnothing(kernel.measures) ? "NO" :
        !isnothing(kernel.root) && !isnothing(kernel.labelSeq) && !isnothing(kernel.measures) ? "YES" : "UNKNOWN"
    )
    print(io, text)
end

struct QueItem
    node::Node
    gId::Int
    uSymb::Symbol
end

function Base.in(key::UInt, children::Vector{Tuple{Float64,Node}})::Bool
    for (_, node) in children
        if node.hash == key
            return true
        end
    end

    return false
end

function getfirst(children::Vector{Tuple{Float64,Node}}, key::UInt)::Node
    for (_, node) in children
        if node.hash == key
            return node
        end
    end

    throw(ErrorException("wrong"))
end

function fit!(
    kernel::TwwlPrim, mgs::Vector{MetaGraphsNext.MetaGraph};
    updateMeasure::Bool=true, verbose::Bool=false
)
    if updateMeasure
        _updateUniqueMeasure!(mgs; measureSymb=kernel.measureSymb)
    else
        _checkNodeInfo(mgs, kernel.measureSymb)
    end
    _checkNodeInfo(mgs, kernel.labelSymb)

    N = length(mgs)
    labelSeq = Vector{AbstractMatrix}()
    measures = [
        Float64[
            mg[label_for(mg, u)][kernel.measureSymb]
            for u in 1:nv(mg)
        ]
        for mg in mgs
    ]
    root = Node(hash(nothing), -1, ones(Float64, N), [])
    que = Queue{QueItem}()

    kernel.N = N
    kernel.root = root
    kernel.labelSeq = labelSeq
    kernel.measures = measures

    for (i, mg) in enumerate(mgs)
        lseq = zeros(UInt, nv(mg), kernel.H + 1)
        for uSymb in labels(mg)
            u = code_for(mg, uSymb)
            labelHash = hash(mg[uSymb][kernel.labelSymb])
            lseq[u, 1] = labelHash

            if in(labelHash, root.children)
                child = getfirst(root.children, labelHash)
            else
                child = Node(labelHash, root.depth + 1, zeros(Float64, N), [])
                push!(root.children, (0.5, child))
            end
            enqueue!(que, QueItem(child, i, uSymb))
        end
        push!(labelSeq, lseq)
    end

    while !isempty(que)
        item = dequeue!(que)
        node, i, uSymb = item.node, item.gId, item.uSymb
        depth = node.depth
        mg = mgs[i]

        node.Γ[i] += mg[uSymb][kernel.measureSymb]
        depth == kernel.H && continue

        u = code_for(mg, uSymb)
        lseq = labelSeq[i]
        labelHash = lseq[u, depth+1]
        labelHashes = lseq[code_for.(Ref(mg), neighbor_labels(mg, uSymb)), depth+1] |> sort
        nxt = hash(labelHash, hash(labelHashes))
        lseq[u, depth+2] = nxt

        if in(nxt, node.children)
            child = getfirst(node.children, nxt)
        else
            child = Node(nxt, depth + 1, zeros(Float64, N), [])
            push!(node.children, (0.5, child))
        end
        enqueue!(que, QueItem(child, i, uSymb))
    end

    return
end

"""
    treeMetric(kernel::TwwlPrim)::AbstractMatrix

    This function computes the Wasserstein Weisfeiler-Lehman distance matrix for labelled graphs.
    This function faithfully reproduces the pseudocode presented in the paper.
    The return value is the same with `treeMetric(kernel::Twwl)`, which is faster than this function.
"""
function treeMetric(kernel::TwwlPrim; verbose::Bool=false)::AbstractMatrix
    (isnothing(kernel.N) || isnothing(kernel.root)) &&
        throw(ErrorException("`kernel` must be applied `fit!`"))

    N = kernel.N
    dist = zeros(Float64, N, N)
    _treeMetric!(dist, kernel.root; verbose=verbose)

    dist
end

function _treeMetric!(dist::AbstractMatrix, node::Node; verbose::Bool=false)
    for (wgt, child) in node.children
        _treeMetric!(dist, child)
        dist .+= abs.(child.Γ .- child.Γ') .* wgt
    end
end

"""
    treeMetricLP(kernel::TwwlPrim)

    This function computes the Wasserstein Weisfeiler-Lehman distance matrix for labelled graphs,
    by solving a linear programming problem.
"""
function treeMetricLP(kernel::TwwlPrim; verbose::Bool=false)::AbstractMatrix
    (isnothing(kernel.N) || isnothing(kernel.labelSeq) || isnothing(kernel.measures)) &&
        throw(ErrorException("`kernel` must be applied `fit!`"))

    N = kernel.N
    dist = zeros(Float64, N, N)
    pbar = Progress(fld(N * (N - 1), 2); enabled=verbose, desc="treeMetricLP")
    for i in 1:N
        lseqi = kernel.labelSeq[i]
        μ = kernel.measures[i]
        @assert isapprox(sum(μ), 1.0; atol=1e-8)

        ni = length(μ)
        for j in i+1:N
            lseqj = kernel.labelSeq[j]
            ν = kernel.measures[j]
            @assert isapprox(sum(ν), 1.0; atol=1e-8)
            nj = length(ν)

            costs = pairwise(Hamming(), lseqi, lseqj; dims=1)
            model = Model(HiGHS.Optimizer)
            set_attribute(model, "threads", 1)
            set_attribute(model, "log_to_console", false)
            @variable(model, P[1:ni, 1:nj] .>= 0)
            @objective(model, MIN_SENSE, dot(costs, P))
            @constraint(model, P * ones(nj) .== μ)
            @constraint(model, P' * ones(ni) .== ν)
            optimize!(model)

            (termination_status(model) != OPTIMAL || primal_status(model) != FEASIBLE_POINT) &&
                throw(ErrorException("Failed to optimize in ($(i), $(j))"))

            opt = objective_value(model)
            dist[i, j] = opt
            dist[j, i] = opt
            next!(pbar; showvalues=[("i", i), ("j", j)])
        end
    end

    dist
end
